# This file was generated by GoReleaser. DO NOT EDIT.
cask "mailrules" do
  version "0.1.1"

  on_macos do
    on_arm do
      sha256 "5ea4b9223c7064d758c8f3fcc320e923ea51fffec285bda4a6958a922407b509"
      url "https://github.com/TurtleByte-IN/mailrules/releases/download/v#{version}/mailrules_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "1fb6b6ab19c5d1e3dc27ae8b07fc479551d6aed72a745ec16fbc686f6f630089"
      url "https://github.com/TurtleByte-IN/mailrules/releases/download/v#{version}/mailrules_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "7173609f6f257a57280f198f8500c03d750e04616b3cc7ca749bedd9529eaa49"
      url "https://github.com/TurtleByte-IN/mailrules/releases/download/v#{version}/mailrules_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "e55ae89200dc194215d1491af41a3dbc06a7ab0fa22eb0ecb8d363d75677224d"
      url "https://github.com/TurtleByte-IN/mailrules/releases/download/v#{version}/mailrules_#{version}_linux_amd64.tar.gz"
    end
  end

  name "mailrules"
  desc "Sorts incoming email over IMAP with rules written in plain English"
  homepage "https://github.com/TurtleByte-IN/mailrules"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mailrules"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mailrules"]
    end
  end

  # No zap stanza required
end
