# This file was generated by GoReleaser. DO NOT EDIT.
cask "mailrules" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "8bf47c086c86237c53914f1b78c65dabbbf1a51f19be4942caa3b14750605195"
      url "https://github.com/TurtleByte-IN/mailrules/releases/download/v#{version}/mailrules_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "09c794e210f60badd90f23289b5e4c3bc7444a90275edf8e79fd93ed5592f9e9"
      url "https://github.com/TurtleByte-IN/mailrules/releases/download/v#{version}/mailrules_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "0fd58dca23a1ddcfca0b08b9427365ea089431b94546fdbb84199ccedb60d060"
      url "https://github.com/TurtleByte-IN/mailrules/releases/download/v#{version}/mailrules_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "2ce8a24ef1acf49dc7572ede3f4d38e7c25c0999e4b8c992d81b4464ff471f24"
      url "https://github.com/TurtleByte-IN/mailrules/releases/download/v#{version}/mailrules_#{version}_linux_amd64.tar.gz"
    end
  end

  name "mailrules"
  desc "Sorts incoming email over IMAP with rules written in plain English"
  homepage "https://github.com/TurtleByte-IN/mailrules"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mailrules"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mailrules"]
    end
  end

  # No zap stanza required
end
