# This file was generated by GoReleaser. DO NOT EDIT.
cask "mailrules" do
  version "0.1.4"

  on_macos do
    on_arm do
      sha256 "7d666e69593328101fd074942cd425e8e60b75bee4dd8e2e5e447d1a2441c3d4"
      url "https://github.com/TurtleByte-IN/mailrules/releases/download/v#{version}/mailrules_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "a0f46b059d0b22047957e1667babdcf9eed8e846def10cd85bc54be8020aa0d5"
      url "https://github.com/TurtleByte-IN/mailrules/releases/download/v#{version}/mailrules_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "fade7fcc869e3af06f92dfc1425abfc4ea85c6a0fa8b74a1e6ba16b3dddeb450"
      url "https://github.com/TurtleByte-IN/mailrules/releases/download/v#{version}/mailrules_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "2890a60a8d2c56774adc9c14b2b474da0ee7d56d346df11b52ec78058d480ad3"
      url "https://github.com/TurtleByte-IN/mailrules/releases/download/v#{version}/mailrules_#{version}_linux_amd64.tar.gz"
    end
  end

  name "mailrules"
  desc "Sorts incoming email over IMAP with rules written in plain English"
  homepage "https://github.com/TurtleByte-IN/mailrules"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mailrules"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mailrules"]
    end
  end

  # No zap stanza required
end
